# Generated by Django 4.2.15 on 2026-01-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="account_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("us_dollar", "US Dollar"),
                    ("pound_sterling", "Pound Sterling"),
                    ("kenya_shilling", "Kenya Shilling"),
                ],
                max_length=20,
                null=True,
                verbose_name="Account Currency",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[("current", "Current"), ("savings", "Savings")],
                max_length=20,
                null=True,
                verbose_name="Account Type",
            ),
        ),
    ]
