# Generated by Django 4.2.15 on 2026-01-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_alter_profile_account_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="account_currency",
            field=models.CharField(
                blank=True,
                choices=[("us_dollar", "US Dollar"), ("euro", "Euro"), ("INR", "INR")],
                max_length=20,
                null=True,
                verbose_name="Account Currency",
            ),
        ),
    ]
